fix compiler error - shadows a  previous local
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g  -ggdb3 -fPIC -fvisibility=hidden -std=c99 -Wall -Wextra -Werror -Wno-unused-parameter -Wno-implicit-fallthrough -Iinclude -I../../src/interfaces/libpq -I. -I. -I../../src/include  -DLOCK_DEBUG -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/job_metadata.o src/job_metadata.c -MMD -MP -MF .deps/job_metadata.Po
src/job_metadata.c: In function ‘ParseSchedule’:
src/job_metadata.c:1526:10: error: declaration of ‘schedule’ shadows a previous local [-Werror=shadow=compatible-local]
 1526 |   entry *schedule = calloc(sizeof(entry), sizeof(char));
      |          ^~~~~~~~
src/job_metadata.c:1514:9: note: shadowed declaration is here
 1514 |  entry *schedule = parse_cron_entry(scheduleText);
      |         ^~~~~~~~
cc1: all warnings being treated as errors
make: *** [../../src/Makefile.global:949: src/job_metadata.o] Error 1