Some fix to build on FreeBSD 14.3 and PostgreSQL 18 beta 1 (#394)
* Some fix to build on FreeBSD 14.3 and Postgresql 18 beta 1
1. declaring static variabile in some files
2. restrored old 384c9c5 commit: with PostgreSQL 18 I had:

src/pg_cron.c:2268:71: error: too few arguments to function call, expected 7, have 6
 2268 |                 PortalDefineQuery(portal, NULL, sql, commandTag, plantree_list, NULL);
      |                 ~~~~~~~~~~~~~~~~~                                                   ^
/usr/local/include/postgresql/server/utils/portal.h:239:13: note: 'PortalDefineQuery' declared here
  239 | extern void PortalDefineQuery(Portal portal,
      |             ^                 ~~~~~~~~~~~~~~
  240 |                                                           const char *prepStmtName,
      |                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~
  241 |                                                           const char *sourceText,
      |                                                           ~~~~~~~~~~~~~~~~~~~~~~~
  242 |                                                           CommandTag commandTag,
      |                                                           ~~~~~~~~~~~~~~~~~~~~~~
  243 |                                                           List *stmts,
      |                                                           ~~~~~~~~~~~~
  244 |                                                           CachedPlan *cplan,
      |                                                           ~~~~~~~~~~~~~~~~~~
  245 |                                                           CachedPlanSource *plansource);
      |                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* Fix static variable declaration: added -Wno-missing-variable-declarations in Makefile